// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAAG-DktMceVxG8dCUx6iuTA_TwWfs5IGQ',
    appId: '1:185609658871:web:3c6872ab576e651e668ef2',
    messagingSenderId: '185609658871',
    projectId: 'mlimi-app-b1c28',
    authDomain: 'mlimi-app-b1c28.firebaseapp.com',
    storageBucket: 'mlimi-app-b1c28.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBgbDzU3ck3ShnIGOzqrjVbOT5s7aRYMZY',
    appId: '1:185609658871:android:f1af015fc612853b668ef2',
    messagingSenderId: '185609658871',
    projectId: 'mlimi-app-b1c28',
    storageBucket: 'mlimi-app-b1c28.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAAG-DktMceVxG8dCUx6iuTA_TwWfs5IGQ',
    appId: '1:185609658871:web:e6cf294a533bc222668ef2',
    messagingSenderId: '185609658871',
    projectId: 'mlimi-app-b1c28',
    authDomain: 'mlimi-app-b1c28.firebaseapp.com',
    storageBucket: 'mlimi-app-b1c28.firebasestorage.app',
  );
}
